#
# Module manifest for module 'ModuleWriteError'
#
# Generated by: Thell Fowler
#
# Generated on: 1/13/2010
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'ModuleWriteError.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '64a09a69-e432-43ab-907e-18470da14621'

# Author of this module
Author = 'Thell Fowler'

# Company or vendor of this module
CompanyName = 'Notepad++ Community'

# Copyright statement for this module
Copyright = 'GNU GPL v3'

# Description of the functionality provided by this module
Description = 'Generic module and advanced function aware exception class and error record generator for use with Write-Error and $PSCmdlet.WriteError() allowing embedding of the module name and prefixed or non-prefixed advanced function name into error messages.`n'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @('FunctionInfo.types.ps1xml')

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = 'ModuleWriteError.psm1'

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}

